---
# tasks file for nginx_proxy

- name: Установка Nginx
  apt:
    name: "nginx"
    state: present

- name: Настройка редиректа
  ansible.builtin.template:
    src: redirect.j2
    dest: /etc/nginx/sites-enabled/nginx.conf
  when: "'nginx_proxy' in inventory_hostname" # Выполнится только тогда, когда в имени есть nginx_proxy
  notify: "Nginx Reloader"
