---
- name: Установка стандартных пакетов
  hosts: all
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка и настройка nginx c кастомной страницей
  hosts: nginx_app
  roles:
    - role: nginx_app
  tags:
    - nginx_app

- name: Установка и настройка проксирующего nginx
  hosts: nginx_proxy
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy